name: Native-Image

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version number'
        required: true

jobs:
  build:
    name: Build native image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV          

      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            togetherds/mihomo-exporter:${{ github.event.inputs.version }}-${{ env.PLATFORM_PAIR }}
            togetherds/mihomo-exporter:latest-${{ env.PLATFORM_PAIR }}

  create-manifests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create and push manifest
        run: |
          VERSION=${{ github.event.inputs.version }}
          docker manifest create togetherds/mihomo-exporter:${VERSION} \
            togetherds/mihomo-exporter:${VERSION}-linux-amd64 \
            togetherds/mihomo-exporter:${VERSION}-linux-arm64
          docker manifest create togetherds/mihomo-exporter:latest \
            togetherds/mihomo-exporter:latest-linux-amd64 \
            togetherds/mihomo-exporter:latest-linux-arm64
          docker manifest push togetherds/mihomo-exporter:${VERSION}
          docker manifest push togetherds/mihomo-exporter:latest
